[project]
name = "paperpilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lx", email = "834659376@qq.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "langgraph>=1.2.11",
    "pydantic>=2.13.5",
    "pymupdf>=1.28.2",
    "python-multipart>=0.0.32",
    "sentence-transformers>=6.0.1",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
paperpilot = "paperpilot:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
