"""生成**自带 demo 论文**（`demo/demo_paper.pdf`）——完全合成的示例内容，无第三方版权。

为什么自带一篇：招聘方/评审不该为了看一眼产品去 arXiv 找 PDF。
这篇"论文"包含标题 / 摘要 / 引言 / 方法 / 结果（含表格数值）/ 结论，
足以跑通完整链路：摄取 → 报告 → 检索 → 带引用的问答。

用法（改内容后重新生成）：
    uv run python demo/make_demo_pdf.py
"""
from __future__ import annotations

from pathlib import Path

import fitz

OUT = Path(__file__).resolve().parent / "demo_paper.pdf"

TITLE = "DualTower: A Minimal Demo Paper for PaperPilot"

SECTIONS: list[tuple[str, list[str]]] = [
    ("Abstract", [
        "This demo paper is synthetic and exists only to exercise the reading pipeline.",
        "We propose a dual-tower retrieval architecture for composed image retrieval.",
        "The method reaches 87.3% accuracy on the public benchmark.",
    ]),
    ("1 Introduction", [
        "Composed image retrieval takes a reference image plus a modification text as input.",
        "Existing single-tower models entangle visual and textual signals in one encoder.",
        "This demo paper serves as a fixed, freely redistributable example document.",
    ]),
    ("2 Method", [
        "We propose a dual-tower retrieval architecture that encodes images and text separately.",
        "The two towers are aligned with a contrastive learning objective over 1,024 batches.",
        "A lightweight reranker then fuses the two similarity scores.",
    ]),
    ("3 Results", [
        "The method reaches 87.3% accuracy on the public benchmark.",
        "Table 1 reports the accuracy of each variant on the test set.",
        "| Model | Accuracy | Note |",
        "| Single tower | 84.1 | baseline |",
        "| Dual tower (ours) | 87.3 | +3.2 |",
        "| Dual tower + rerank | 88.0 | +3.9 |",
        "Ablation shows the reranker contributes 0.7 accuracy points.",
    ]),
    ("4 Conclusion", [
        "We presented a dual-tower retrieval architecture with a reranker.",
        "The demo document is intentionally short so the pipeline finishes quickly.",
    ]),
]

FOOTER = ("Synthetic demo paper generated by demo/make_demo_pdf.py — "
          "free to copy, modify and redistribute (MIT).")


def build() -> Path:
    doc = fitz.open()
    page = doc.new_page()
    y = 72.0
    page.insert_text((72, y), TITLE, fontsize=17)
    y += 26
    page.insert_text((72, y), FOOTER, fontsize=8.5, color=(0.45, 0.45, 0.45))
    y += 26

    for heading, lines in SECTIONS:
        if y > 720:                       # 简单分页
            page = doc.new_page()
            y = 72.0
        page.insert_text((72, y), heading, fontsize=13)
        y += 20
        for ln in lines:
            if y > 730:
                page = doc.new_page()
                y = 72.0
            page.insert_text((72, y), ln, fontsize=10.5)
            y += 15
        y += 12

    doc.save(str(OUT))
    doc.close()
    return OUT


if __name__ == "__main__":
    p = build()
    print(f"已生成：{p}（{p.stat().st_size / 1024:.1f} KB）")
